export const ALBUMDATA_LOADING = 'ALBUMDATA_LOADING';
export const ALBUMDATA_LOADING_COMPLETED = 'ALBUMDATA_LOADING_COMPLETED';
export const LOAD_ALBUMDATA = 'LOAD_ALBUMDATA';
export const ALBUM_TOGGLE_EXPANDCOLLAPSE = 'ALBUM_TOGGLE_EXPANDCOLLAPSE';
export const ALL_TOGGLE_EXPANDCOLLAPSE = 'ALL_TOGGLE_EXPANDCOLLAPSE';